INSERT INTO issues (issue_id, title, description, location, date, supports, category, status) VALUES
('ISSUE-0001', 'Pothole on Main Street', 'Pothole on Main Street. Reported by local residents, urgent attention required.', 'Sector 9', '2024-01-17', 56, 'Electricity', 'In Progress'),
('ISSUE-0002', 'Streetlight Not Working', 'Streetlight Not Working. Local authority inspection requested.', 'Sector 7', '2024-01-14', 2, 'Internet', 'Resolved'),
('ISSUE-0003', 'Water Leakage Near Park', 'Water Leakage Near Park. Causing major inconvenience to daily commuters.', 'Sector 5', '2023-02-27', 11, 'Internet', 'Closed'),
('ISSUE-0004', 'Power Outage in Sector 5', 'Power Outage in Sector 5. Causing major inconvenience to daily commuters.', 'Sector 6', '2024-08-01', 27, 'Internet', 'Closed'),
('ISSUE-0005', 'Slow Internet in Colony', 'Slow Internet in Colony. Several complaints received from citizens in the area.', 'Sector 10', '2023-06-02', 79, 'Water', 'Closed'),
('ISSUE-0006', 'Broken Bus Stop Shelter', 'Broken Bus Stop Shelter. Several complaints received from citizens in the area.', 'Sector 16', '2024-01-28', 1, 'Public Transport', 'Open'),
('ISSUE-0007', 'Overflowing Garbage Bin', 'Overflowing Garbage Bin. Local authority inspection requested.', 'Sector 10', '2024-08-18', 33, 'Road', 'Open'),
('ISSUE-0008', 'Manhole Cover Missing', 'Manhole Cover Missing. Reported by local residents, urgent attention required.', 'Sector 1', '2023-05-30', 93, 'Electricity', 'Resolved'),
('ISSUE-0009', 'Traffic Signal Malfunction', 'Traffic Signal Malfunction. Safety hazard, needs urgent government response.', 'Sector 4', '2023-04-15', 25, 'Electricity', 'In Progress'),
('ISSUE-0010', 'Public Toilet Needs Repair', 'Public Toilet Needs Repair. Several complaints received from citizens in the area.', 'Sector 12', '2024-03-09', 79, 'Electricity', 'Closed'),
('ISSUE-0011', 'Playground Equipment Broken', 'Playground Equipment Broken. Safety hazard, needs urgent government response.', 'Sector 1', '2023-11-24', 65, 'Road', 'Open'),
('ISSUE-0012', 'Noisy Generator at Night', 'Noisy Generator at Night. Critical issue, should be prioritized for resolution.', 'Sector 20', '2023-06-15', 80, 'Electricity', 'Open'),
('ISSUE-0013', 'Damaged Footpath Tiles', 'Damaged Footpath Tiles. Needs immediate repair to avoid accidents.', 'Sector 6', '2023-10-30', 80, 'Public Transport', 'Open'),
('ISSUE-0014', 'Flooded Underpass After Rain', 'Flooded Underpass After Rain. Area council has already been informed multiple times.', 'Sector 13', '2024-07-20', 38, 'Public Transport', 'Open'),
('ISSUE-0015', 'Garbage Collection Delayed', 'Garbage Collection Delayed. Critical issue, should be prioritized for resolution.', 'Sector 10', '2023-07-24', 55, 'Water', 'Resolved'),
('ISSUE-0016', 'Illegal Parking on Main Road', 'Illegal Parking on Main Road. Residents demanding quick action on this matter.', 'Sector 3', '2023-07-30', 64, 'Public Transport', 'Resolved'),
('ISSUE-0017', 'Street Vendor Blocking Path', 'Street Vendor Blocking Path. Safety hazard, needs urgent government response.', 'Sector 11', '2023-11-28', 75, 'Road', 'In Progress'),
('ISSUE-0018', 'Trees Blocking Street Lights', 'Trees Blocking Street Lights. Causing major inconvenience to daily commuters.', 'Sector 13', '2024-08-11', 85, 'Water', 'Open'),
('ISSUE-0019', 'Uncollected Dead Animal', 'Uncollected Dead Animal. Residents demanding quick action on this matter.', 'Sector 3', '2023-09-24', 86, 'Internet', 'Closed'),
('ISSUE-0020', 'Water Pump Malfunctioning', 'Water Pump Malfunctioning. Safety hazard, needs urgent government response.', 'Sector 14', '2024-03-25', 55, 'Public Transport', 'Closed'),
('ISSUE-0021', 'Broken Handrail at Bridge', 'Broken Handrail at Bridge. Safety hazard, needs urgent government response.', 'Sector 2', '2023-01-28', 58, 'Public Transport', 'Resolved'),
('ISSUE-0022', 'School Bus Late Everyday', 'School Bus Late Everyday. Causing major inconvenience to daily commuters.', 'Sector 7', '2023-02-20', 71, 'Water', 'In Progress'),
('ISSUE-0023', 'Mosquito Breeding in Drain', 'Mosquito Breeding in Drain. Problem persisting for the last two weeks.', 'Sector 14', '2023-05-30', 78, 'Internet', 'Closed'),
('ISSUE-0024', 'Library AC Not Working', 'Library AC Not Working. Residents demanding quick action on this matter.', 'Sector 13', '2023-03-13', 36, 'Internet', 'Closed'),
('ISSUE-0025', 'Dirty Drinking Water Supply', 'Dirty Drinking Water Supply. Area council has already been informed multiple times.', 'Sector 10', '2024-07-31', 25, 'Internet', 'In Progress'),
('ISSUE-0026', 'Poor Mobile Network Signal', 'Poor Mobile Network Signal. Safety hazard, needs urgent government response.', 'Sector 3', '2024-03-21', 44, 'Internet', 'Closed'),
('ISSUE-0027', 'Gas Leakage Complaint', 'Gas Leakage Complaint. Residents demanding quick action on this matter.', 'Sector 17', '2023-12-30', 21, 'Electricity', 'Open'),
('ISSUE-0028', 'Noise Pollution From Factory', 'Noise Pollution From Factory. Several complaints received from citizens in the area.', 'Sector 17', '2023-04-07', 16, 'Public Transport', 'Closed'),
('ISSUE-0029', 'Dustbin Shortage in Area', 'Dustbin Shortage in Area. Reported by local residents, urgent attention required.', 'Sector 19', '2023-01-17', 36, 'Water', 'Resolved'),
('ISSUE-0030', 'Broken Divider on Road', 'Broken Divider on Road. Critical issue, should be prioritized for resolution.', 'Sector 20', '2023-02-11', 10, 'Public Transport', 'Resolved'),
('ISSUE-0031', 'Stray Dogs Menace', 'Stray Dogs Menace. Safety hazard, needs urgent government response.', 'Sector 10', '2023-10-15', 18, 'Public Transport', 'In Progress'),
('ISSUE-0032', 'Water Tank Overflow', 'Water Tank Overflow. Problem persisting for the last two weeks.', 'Sector 7', '2024-07-22', 86, 'Public Transport', 'Closed'),
('ISSUE-0033', 'Fire Hydrant Missing', 'Fire Hydrant Missing. Causing major inconvenience to daily commuters.', 'Sector 18', '2023-03-05', 57, 'Public Transport', 'Open'),
('ISSUE-0034', 'Park Benches Damaged', 'Park Benches Damaged. Problem persisting for the last two weeks.', 'Sector 8', '2023-06-23', 69, 'Public Transport', 'Resolved'),
('ISSUE-0035', 'CCTV Camera Not Working', 'CCTV Camera Not Working. Problem persisting for the last two weeks.', 'Sector 16', '2023-03-15', 4, 'Internet', 'Resolved'),
('ISSUE-0036', 'Illegal Dumping of Waste', 'Illegal Dumping of Waste. Safety hazard, needs urgent government response.', 'Sector 5', '2024-02-08', 25, 'Electricity', 'Resolved'),
('ISSUE-0037', 'Unmarked Speed Breaker', 'Unmarked Speed Breaker. Local authority inspection requested.', 'Sector 18', '2023-03-14', 82, 'Public Transport', 'Open'),
('ISSUE-0038', 'Street Flooding After Drain Blockage', 'Street Flooding After Drain Blockage. Reported by local residents, urgent attention required.', 'Sector 17', '2024-04-03', 0, 'Internet', 'Resolved'),
('ISSUE-0039', 'Rickshaw Stand Blocking Gate', 'Rickshaw Stand Blocking Gate. Safety hazard, needs urgent government response.', 'Sector 19', '2023-11-27', 1, 'Public Transport', 'Closed'),
('ISSUE-0040', 'Public Transport Delay', 'Public Transport Delay. Local authority inspection requested.', 'Sector 18', '2023-03-09', 47, 'Electricity', 'Open'),
('ISSUE-0041', 'Electric Pole Leaning', 'Electric Pole Leaning. Reported by local residents, urgent attention required.', 'Sector 9', '2024-05-18', 3, 'Water', 'In Progress'),
('ISSUE-0042', 'Playground Lights Broken', 'Playground Lights Broken. Causing major inconvenience to daily commuters.', 'Sector 12', '2023-09-20', 55, 'Water', 'Open'),
('ISSUE-0043', 'Library Books Missing', 'Library Books Missing. Safety hazard, needs urgent government response.', 'Sector 5', '2023-03-12', 74, 'Road', 'In Progress'),
('ISSUE-0044', 'Overcharging by Taxi Drivers', 'Overcharging by Taxi Drivers. Local authority inspection requested.', 'Sector 15', '2023-07-27', 39, 'Internet', 'Resolved'),
('ISSUE-0045', 'Water Tanker Delay', 'Water Tanker Delay. Needs immediate repair to avoid accidents.', 'Sector 12', '2023-10-07', 96, 'Internet', 'Closed'),
('ISSUE-0046', 'Dust Pollution From Construction', 'Dust Pollution From Construction. Causing major inconvenience to daily commuters.', 'Sector 5', '2023-02-07', 63, 'Internet', 'Resolved'),
('ISSUE-0047', 'Leaking Sewage Pipe', 'Leaking Sewage Pipe. Local authority inspection requested.', 'Sector 3', '2024-01-12', 93, 'Road', 'Closed'),
('ISSUE-0048', 'Overhead Cable Hanging Loose', 'Overhead Cable Hanging Loose. Causing major inconvenience to daily commuters.', 'Sector 9', '2023-10-24', 1, 'Road', 'Resolved'),
('ISSUE-0049', 'Unhygienic Food Stall', 'Unhygienic Food Stall. Several complaints received from citizens in the area.', 'Sector 14', '2023-06-05', 8, 'Public Transport', 'Open'),
('ISSUE-0050', 'Road Divider Plants Dry', 'Road Divider Plants Dry. Local authority inspection requested.', 'Sector 12', '2023-02-15', 74, 'Internet', 'Open');